version: '3.9'
services:
  console:
    build: .
    environment:
      BACKEND_URL: http://backend:4000
      NEXT_PUBLIC_BACKEND_URL: http://localhost:4000
    ports:
      - '3000:3000'
    depends_on:
      - backend
  backend:
    image: ghcr.io/evergreen-os/selfhost-backend:latest
    environment:
      PORT: 4000
    ports:
      - '4000:4000'
